INSERT INTO global_sections (id, type, title, subtitle, content, is_active, order_index) VALUES 
('sec-hero', 'hero', 'GIVENEEDS', '당신의 마케팅을 위한 모든 것', '{}', false, 0),
('sec-services', 'products', '주요 솔루션', '고객의 브랜드를 성장시키는 방법', '{"items":[{"category":"DATA","title":"퍼포먼스 마케팅","desc":"Meta, Google 매체 최적화를 통한 ROAS 극대화 및 고객 획득 비용(CAC) 절감"},{"category":"GROWTH","title":"CRM 마케팅","desc":"행동 데이터 기반의 세그먼트 타겟팅으로 고객 라이프타임 밸류(LTV) 상승"},{"category":"CREATIVE","title":"브랜드 콘텐츠","desc":"고관여 타겟을 매료시키는 심미적이고 논리적인 영상/디자인 애셋 제작"}]}', false, 1),
('sec-video', 'video', '기브니즈 알아보기', '마케팅의 새로운 기준을 제시하는 기브니즈를 영상으로 만나보세요.', '{}', true, 2),
('sec-testimonials', 'testimonials', '파트너 사례', '숫자로 입증된 결과', '{"items":[{"name":"K대표","company":"IT 스타트업","text":"기브니즈 협업 후 CPA가 40% 이상 감소했습니다.","rating":5}]}', true, 3),
('sec-faq', 'faq', 'FAQ', '자주 묻는 질문', '{"items":[{"question":"의뢰 프로세스는 어떻게 되나요?","answer":"초기 킥오프 미팅부터 리포트 발행까지 체계적으로 진행됩니다."}]}', true, 4),
('sec-hook', 'hook', '누구나 해결할 수 있는 건', '이 아닙니다.', '{"highlight":"마케팅","footer":"혼자 해결할 수 없는 부분."}', true, 5),
('sec-stats', 'stats', '숫자로 입증된 결과', '기브니즈가 만든 변화', '{"items":[{"label":"함께한 클라이언트","value":"490+"},{"label":"재계약율","value":"92%"},{"label":"고객 만족도","value":"95%"}]}', true, 6),
('sec-identity', 'identity', '기브니즈가 누구도 해결하지 못했던 부분을 채워 드리겠습니다.', '', '{"left":{"title":"GIVE","desc":"건네주다"},"middle":{"title":"NEEDS","desc":"원하는 것을"},"right":{"title":"GIVENEEDS","desc":"진정 원하는 가치를 전달하는 마케팅"}}', true, 7),
('sec-product-detail', 'product_detail', 'OUR SOLUTION', '기브니즈만의 압도적인 마케팅 솔루션', '{"items":[{"id":"ads","title":"Strategic Ads","desc":"카페 바이럴, 블로그, 언론보도, 메타 및 파워링크 최적화 운영","detail_title":"STRATEGIC ADS","detail_desc":"카페 바이럴, 블로그 마케팅, 언론보도 송출, Meta Ads 및 파워링크 최적화 운영","detail_sub":"단순 배포가 아닌 상위 노출과 고관여 타겟의 유입을 목적으로 하는 전략적 광고 시스템.","icon":"MessageSquare","slug":"strategic-ads","color":"#1E4181"},{"id":"growth","title":"Growth & Review","desc":"네이버/스토어/구글/카카오 리뷰 관리 및 인스타 전용 계정 성장","detail_title":"GROWTH & REVIEW","detail_desc":"네이버/스토어/구글/카카오 리뷰 관리 및 인스타 전용 계정 성장","detail_sub":"부정적 여론 방어와 진성 리뷰 축적, 브랜드 소셜 파워 구축으로 전환율을 극대화합니다.","icon":"Star","slug":"growth-review","color":"#16A34A"},{"id":"local","title":"Local Optimize","desc":"스토어, 플레이스, 070 서비스, 카카오맵 노출의 개별적 세분화 최적화","detail_title":"LOCAL OPTIMIZE","detail_desc":"스토어, 플레이스, 070 서비스, 카카오맵 노출의 개별적 세분화 최적화","detail_sub":"내 주변 검색 시 최상단 노출을 점령하는 지역 기반 검색 최적화 토탈 솔루션.","icon":"MapPin","slug":"local-optimize","color":"#71717A"},{"id":"tech","title":"Tech / Creative","desc":"마케팅 전용 AI 엔진 가동 및 프리미엄 웹/UI/UX 프로덕션","detail_title":"TECH / CREATIVE","detail_desc":"마케팅 전용 AI 엔진 가동 및 프리미엄 웹/UI/UX 프로덕션","detail_sub":"초격차 AI 기술력과 감각적 디자인의 결합으로 브랜드 가치를 극대화합니다.","icon":"Cpu","slug":"tech-creative","color":"#18181B"}]}', true, 8),
('sec-ai-strategy', 'ai_strategy', 'AI 전략 가이드', '기브니즈 AI로 5분만에 내 비즈니스 맞춤형 전략 알아보기', '{}', true, 9);